/**
 * actions in auth
 */
export const SIGN_IN_LOCAL = "SIGN_IN_LOCAL";
export const SIGN_IN_LOCAL_SUCCESS = "SIGN_IN_LOCAL_SUCCESS";
export const SIGN_UP_LOCAL = "SIGN_UP_LOCAL";
export const SIGN_UP_LOCAL_SUCCESS = "SIGN_UP_LOCAL_SUCCESS";
export const GET_USER_INFO = "GET_USER_INFO";
export const GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS";
export const SIGN_OUT = "SIGN_OUT";

export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

/**
 * actions in exam
 */
export const GET_EXAM_NUMBER = "GET_EXAM_NUMBER";
export const GET_EXAM_INFO = "GET_EXAM_INFO";
export const GET_EXAM_INFO_FAIL = "GET_EXAM_INFO_FAIL";
export const GET_EXAM_INFO_SUCCESS = "GET_EXAM_INFO_SUCCESS";
export const GET_KANJI_SKILL_MONDAI = "GET_KANJI_SKILL_MONDAI";
export const GET_KANJI_SKILL_MONDAI_SUCCESS = "GET_KANJI_SKILL_MONDAI_SUCCESS";
export const GET_VOCABULARY_SKILL_MONDAI = "GET_VOCABULARY_SKILL_MONDAI";
export const GET_VOCABULARY_SKILL_MONDAI_SUCCESS = "GET_VOCABULARY_SKILL_MONDAI_SUCCESS";
export const GET_GRAMMAR_SKILL_MONDAI = "GET_GRAMMAR_SKILL_MONDAI";
export const GET_GRAMMAR_SKILL_MONDAI_SUCCESS = "GET_GRAMMAR_SKILL_MONDAI_SUCCESS";
export const GET_READING_SKILL_MONDAI = "GET_READING_SKILL_MONDAI";
export const GET_READING_SKILL_MONDAI_SUCCESS = "GET_READING_SKILL_MONDAI_SUCCESS";
export const GET_LISTENING_SKILL_MONDAI = "GET_LISTENING_SKILL_MONDAI";
export const GET_LISTENING_SKILL_MONDAI_SUCCESS = "GET_LISTENING_SKILL_MONDAI_SUCCESS";
export const GET_ANSWER_LIST = "GET_ANSWER_LIST";
export const GET_ANSWER_LIST_SUCCESS = "GET_ANSWER_LIST_SUCCESS";

export const SEND_ANSWER_LIST_PART1 = "SEND_ANSWER_LIST_PART1";
export const SEND_ANSWER_LIST_PART2 = "SEND_ANSWER_LIST_PART2";
export const SEND_ANSWER_LIST_PART3 = "SEND_ANSWER_LIST_PART3";
export const SEND_ANSWER_LIST_ALL_PART = "SEND_ANSWER_LIST_ALL_PART";

export const GET_RESULT = "GET_RESULT";

export const GET_MARK_PART_1 = "GET_MARK_PART_1";
export const GET_MARK_PART_2 = "GET_MARK_PART_2";
export const GET_MARK_PART_3 = "GET_MARK_PART_3";

export const COMPLETE_PART1 = "COMPLETE_PART1";
export const COMPLETE_PART2 = "COMPLETE_PART2";
export const COMPLETE_PART3 = "COMPLETE_PART3";
export const WATCH_RESULT_DETAIL = "WATCH_RESULT_DETAIL";

/**
 * actions in home
 */
export const GET_EXAM_LIST_DEMO = "GET_EXAM_LIST_DEMO";
export const GET_EXAM_LIST_DEMO_SUCCESS = "GET_EXAM_LIST_DEMO_SUCCESS";

/**
 * refresh
 */
export const REFRESH_EXAM = "REFRESH_EXAM";
export const REFRESH_AUTH = "REFRESH_AUTH";
export const REFRESH_CHOUKAI = "REFRESH_CHOUKAI";
export const REFRESH_RESULT_EXAM = "REFRESH_RESULT_EXAM";

/**
 * action choukai
 */
export const GET_NEXT_CHOUKAI_AUDIO = "GET_NEXT_CHOUKAI_AUDIO";
export const GET_CHOUKAI_DATA = "GET_CHOUKAI_DATA";
export const GET_CHOUKAI_DATA_SUCCESS = "GET_CHOUKAI_DATA_SUCCESS";
export const START_CHOUKAI_AUDIO = "START_CHOUKAI_AUDIO";
export const STOP_CHOUKAI_AUDIO = "STOP_CHOUKAI_AUDIO";